use w5base;
set FOREIGN_KEY_CHECKS=0;
create table simonpkg (
  id         bigint(20) NOT NULL,
  name       varchar(80) NOT NULL,
  cistatus   int(2)      NOT NULL,
    databoss       bigint(20)  default NULL,
    mandator       bigint(20)  default NULL,
    grpid          bigint(20)  default NULL,
    managergrpid   bigint(20)  default NULL,
    description    longtext    default NULL,
    restrictarget  varchar(20) default NULL,
    restriction    longtext    default NULL,
    restrictdate   datetime    default NULL,
    additional     longtext    default NULL,
  comments    longtext     default NULL,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  lastqcheck datetime default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY simonpkg_id (id),key simonpkg_lastqcheck (lastqcheck),
  UNIQUE KEY lastqcheck_name (name),
  UNIQUE KEY `lastqcheck_srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table lnksimonpkgsoftware (
  id           bigint(20) NOT NULL,
  simonpkg     bigint(20) NOT NULL,
  software     bigint(20) NOT NULL,
    minreleasekey  varchar(30),
  comments     longtext    default NULL,
  createdate   datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate   datetime NOT NULL default '0000-00-00 00:00:00',
  createuser   bigint(20) default NULL,
  modifyuser   bigint(20) default NULL,
  editor       varchar(100) NOT NULL default '',
  realeditor   varchar(100) NOT NULL default '',
  srcsys       varchar(100) default 'w5base',
  srcid        varchar(20) default NULL,
  srcload      datetime    default NULL,
  PRIMARY KEY lnksimonpkgsoftware_id (id),
  UNIQUE KEY lnksimonpkgsoftware_vers (simonpkg,software),
  UNIQUE KEY `lnksimonpkgsoftware_srcsys` (srcsys,srcid),
  FOREIGN KEY lnksimonpkgsoftware_fk_software (software) REFERENCES software (id) ON DELETE CASCADE,
  FOREIGN KEY lnksimonpkgsoftware_fk_simonpkg (simonpkg) REFERENCES simonpkg (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table lnksimonpkgrec (
  id           bigint(20) NOT NULL,
  simonpkg     bigint(20) NOT NULL,
  system       bigint(20) NOT NULL,
    reqtarget       varchar(20) NOT NULL,
    exceptstate     varchar(30),
    exceptreqtxt    longtext,
    exceptreqdate   datetime,
    exceptrequestor bigint(20),
    exceptapprstate varchar(30),
    exceptapprdate  datetime,
    exceptapprover  bigint(20), exceptcluster longtext  default NULL,
    exceptrejecttxt longtext,
    notifydate      datetime,
  comments     longtext    default NULL, 
  createdate   datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate   datetime NOT NULL default '0000-00-00 00:00:00',
  createuser   bigint(20) default NULL,
  modifyuser   bigint(20) default NULL,
  editor       varchar(100) NOT NULL default '',
  realeditor   varchar(100) NOT NULL default '',
  srcsys       varchar(100) default 'w5base',
  srcid        varchar(20) default NULL,
  srcload      datetime    default NULL,
  PRIMARY KEY lnksimonpkgrec_id (id),key lnksimonpkgrec_reqtarget (reqtarget),
  UNIQUE KEY lnksimonpkgrec_vers (simonpkg,system),
  UNIQUE KEY `lnksimonpkgrec_srcsys` (srcsys,srcid),
  FOREIGN KEY lnksimonpkgrec_fk_system (system) REFERENCES system (id) ON DELETE CASCADE,
  FOREIGN KEY lnksimonpkgrec_fk_simonpkg (simonpkg) REFERENCES simonpkg (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
set FOREIGN_KEY_CHECKS=1;
alter table lnksimonpkgrec add rejectcnt int(2) default '0';
